# Generated by Django 3.1.4 on 2020-12-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.user')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='UF')),
                ('cnes', models.CharField(max_length=45, verbose_name='CNES')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=40, null=True, verbose_name='Nota Fiscal')),
                ('movimento', models.SmallIntegerField(choices=[(1, 'Entrada'), (2, 'Saida')])),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Fabricante')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.user')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cns', models.CharField(max_length=45, verbose_name='CNS')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=12, verbose_name='RG')),
                ('orgao_expeditor', models.CharField(max_length=100, verbose_name='Orgao Expeditor')),
            ],
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='UF')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.estabelecimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Vacina')),
                ('ml', models.SmallIntegerField(verbose_name='Ml')),
                ('lote', models.PositiveIntegerField(verbose_name='Lote')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.fabricante')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='estabelecimentos',
            field=models.ManyToManyField(through='moduloadministrativo.Vinculo', to='moduloadministrativo.Estabelecimento'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='UF')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.uf')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('saldo', models.PositiveIntegerField(verbose_name='Saldo')),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.estoque')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.vacina')),
            ],
            options={
                'ordering': ['saldo'],
            },
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.municipio'),
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.uf'),
        ),
    ]
