# Generated by Django 3.1.4 on 2020-12-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloadministrativo', '0002_popular_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cnpj',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
    ]
