# Generated by Django 3.1.4 on 2020-12-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloadministrativo', '0003_auto_20201221_1112'),
        ('modulocartaovacina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.estabelecimento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.municipio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulocartaovacina.paciente')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.uf')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloadministrativo.vacina')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='FilaAtendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Atendido'), (2, 'Espera'), (3, 'Não Compareceu')], default=2)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloagendamento.agenda')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
