# Generated by Django 3.1.4 on 2020-12-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
        ('moduloadministrativo', '0003_auto_20201221_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.user')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='CartaoVacina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Vacinação')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moduloadministrativo.estabelecimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modulocartaovacina.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moduloadministrativo.profissional')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moduloadministrativo.vacina')),
            ],
        ),
    ]
